version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: cruddb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - spring-net

  spring-app:
    image: my-user-cactus
    container_name: my-cactus-app
    depends_on:
      - postgres-db
    ports:
      - "8585:8585"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/cruddb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - spring-net

volumes:
  postgres-data:

networks:
  spring-net:
